#ifndef PLAYER_CONSTANTS_H
#define PLAYER_CONSTANTS_H

#define PLAYER_MOTION_DELTA_MULTIPLIER 5
#define PLAYER_FOV_DEG 60
#define PLAYER_FOV_DEG_INC 0.25f
#define PLAYER_W 8.0f
#define PLAYER_H 8.0f
#define PLAYER_INTERACTION_DISTANCE 4.0f
#define PLAYER_ROTATION_SPEED 30.0f
#define PLAYER_ROTATION_STEP 5.0f
#define PLAYER_SPEED 15.0f
#define SPRINT_SPEED_INCREASE 15.0f

#endif